name: Config Auto Forwarder

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '7,22,37,52 * * * *'
    
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Get Date for Cache Key
        id: get-date
        run: echo "date=$(date +'%Y-%U')" >> $GITHUB_ENV
        
      - name: Cache GeoIP Databases
        id: cache-geoip
        uses: actions/cache@v3
        with:
          path: '*.mmdb'
          key: geoip-db-${{ env.date }}
        
      - name: Download GeoIP Databases
        if: steps.cache-geoip.outputs.cache-hit != 'true'
        run: |
          wget -O GeoLite2-Country.mmdb "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb"
          wget -O GeoLite2-ASN.mmdb "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
          DEST_REPO_TOKEN: ${{ secrets.DEST_REPO_TOKEN }} 
          PYTHONUNBUFFERED: "1"
        run: python main.py

      - name: Commit History and Counter
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add history.txt sub_counter.txt
          
          git diff-index --quiet HEAD || git commit -m "Auto-update history and sub counter [skip ci]"
          
          git pull --rebase origin main
          git push
